---
dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
    force: true

driver:
  name: docker

platforms:
  - name: db
    image: geerlingguy/docker-rockylinux8-ansible:latest
    command: ""
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: web
    image: geerlingguy/docker-rockylinux8-ansible:latest
    command: ""
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer, yaml
  inventory:
    links:
      group_vars: ../resources/inventory/group_vars/
      host_vars: ../resources/inventory/host_vars/
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  env:
    ANSIBLE_VERBOSITY: "1"

verifier:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: "1"

lint: |
  set -e
  yamllint .
  ansible-lint .
