---
- name: Prepare - Install locale
  hosts: all
  become: true
  gather_facts: true
  vars:
    server_locale: "en_GB.UTF-8"
  tasks:
    - name: Install locale for CentOS 7
      when: ansible_facts['os_family'] == "CentOS"
      block:
        - name: Allow install of other locals
          ansible.builtin.lineinfile:
            path: /etc/yum.conf
            search_string: "override_install_langs=en_US.utf8"
            state: absent

        - name: Reinstall locales # noqa: package-latest
          ansible.builtin.yum:
            name: glibc-common
            state: latest
