---
- name: Prepare - Install locale
  hosts: all
  become: true
  gather_facts: true
  vars:
    server_locale: "en_GB.UTF-8"
  tasks:
    - name: Install locale for RedHat 7
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] is version('7')
      block:
        - name: Allow install of other locals
          ansible.builtin.lineinfile:
            path: /etc/yum.conf
            search_string: "override_install_langs=en_US.utf8"
            state: absent

        - name: Reinstall locales # noqa: package-latest
          ansible.builtin.yum:
            name: glibc-common
            state: latest

    - name: Install locale for RedHat 8
      ansible.builtin.yum:
        name: glibc-langpack-en
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] is version('7', '>')

    - name: Set the locale # noqa: no-changed-when
      ansible.builtin.command: "localectl set-locale LANG={{ server_locale | quote }}"

- name: Prepare - Disable default postgresl module and install rpm key
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Disable default postgresl module and install rpm key on RedHat 8+
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] is version('7', '>')
      block:
        - name: Disable default Postgres module # noqa command-instead-of-module
          ansible.builtin.command: yum module disable -y postgresql
          register: disable_postgresql_module
          changed_when:
            - "'Disabling modules:' in disable_postgresql_module.stdout"

        - name: Import postgresql rpm key
          ansible.builtin.rpm_key:
            state: present
            key: "{{ postgresql_rpm_gpg_key_pgdg }}"

- name: Prepare - create client SSL certificate
  hosts: web
  become: true
  gather_facts: true
  tasks:
    - name: Install openssl
      ansible.builtin.yum:
        name: openssl
        state: present

    - name: Create self-signed SSL certificate for the client
      ansible.builtin.include_role:
        name: "mirsg.ssl_certificates"
      vars:
        ssl_certificate: "{{ postgresql_client_ssl_certificate }}"

- name: Prepare - install and start crontabs on the db
  hosts: db
  become: true
  gather_facts: true
  tasks:
    - name: Install crontabs
      ansible.builtin.yum:
        name: crontabs
        state: present
    - name: Start crontabs service
      ansible.builtin.service:
        name: crond.service
        state: started
        enabled: true
