---
name: Molecule Test
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "mirsg.provision"

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        scenario:
          - centos7
          - rocky8
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: "mirsg.provision"
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install test dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install rsync
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
